export interface Proveedor {
        id: number,
		registro:number,
		digito:number,
        nombre: String,
        tel: String,
        web: String,
        direccion: String,
        cont1: String,
        tel1: String,
        cargo1: String,
        cont2: String,
        tel2: String,
        cargo2: String,
        comentario: String,
		estado:number,
        correo: String,
		categoria: number,
		calificacion: number,
		favorito: number,
		convenio : number,
		ciudad : String,
		tipo_identidad: number,
		tipo_persona: number,
		regimen: number,
		autoretenedor: number,
		gcontrib: number,
		ica: number,
}